execution:
  checkpointing:
    interval: 10000
rest:
  port: 8081
blob:
  server:
    port: '6124'
taskmanager:
  memory:
    process:
      size: 2048m
  numberOfTaskSlots: 1
parallelism:
  default: 1
jobmanager:
  rpc:
    address: jobmanager
  memory:
    process:
      size: 2048m
state:
  backend: filesystem
  checkpoints:
    dir: file:///tmp/flink-checkpoints
query:
  server:
    port: '6125'
