blob:
  server:
    port: '6124'
taskmanager:
  memory:
    process:
      size: 2048m
  numberOfTaskSlots: 1
logging:
  file:
    path: ./logs/taskmanager/docker-taskmanager.log
  level: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{60} %X{sourceThread} - %msg%n'
jobmanager:
  rpc:
    address: jobmanager
  memory:
    process:
      size: 2048m
query:
  server:
    port: '6125'
execution:
  checkpointing:
    interval: 10000
rest:
  port: 8081
parallelism:
  default: 1
state:
  backend: filesystem
  checkpoints:
    dir: file:///tmp/flink-checkpoints
